language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t arthurburle/react-docker-course -f Dockerfile.dev .

script:
  - docker run -e CI=true arthurburle/react-docker-course npm run test -- --coverage
